### ISSUE TITLE
cannot import name 'Stylesheet' from 'bs4.element'

### ISSUE THREAD

**Issue by hugo-px** [s-4-m-a-n/subscene-API#1]
Hey,
Thanks for uploading this, I have trouble with the other unofficial APIs, I was hoping this one could help, but I have the following issue, when i execute from Jupyter :

import subsceneAPI
from subsceneAPI import subtitle    

ImportError: cannot import name 'Stylesheet' from 'bs4.element' (C:\Users\[...]\anaconda3\lib\site-packages\bs4\element.py)

Could you help ?

Thanks !

**Comment by s-4-m-a-n** [comment]
Thanks for your valuable feedback. Let me check and get back to you.

**Comment by s-4-m-a-n** [comment]
I'm not getting any problem at all here on jupyter notebook. May be you already have installed different version of bs4 on your system which is conflicting the requirements. The possible solutions may be:
1. installing it into a new environment
2. there was a minor mistake in the README. Instead of using "pip install subsceneAPI==0.1" , try "pip install subsceneAPI==0.2"

**Comment by hugo-px** [comment]
I checked and I do have the right versions installed :

`Requirement already satisfied: subsceneAPI in c:\users\\anaconda3\lib\site-packages (0.2)
Requirement already satisfied: requests==2.23.0 in c:\users\\anaconda3\lib\site-packages (from subsceneAPI) (2.23.0)
Requirement already satisfied: beautifulsoup4==4.9.0 in c:\users\\anaconda3\lib\site-packages (from subsceneAPI) (4.9.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\\anaconda3\lib\site-packages (from requests==2.23.0->subsceneAPI) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\\anaconda3\lib\site-packages (from requests==2.23.0->subsceneAPI) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in c:\users\\anaconda3\lib\site-packages (from requests==2.23.0->subsceneAPI) (2.8)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\\anaconda3\lib\site-packages (from requests==2.23.0->subsceneAPI) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\\anaconda3\lib\site-packages (from beautifulsoup4==4.9.0->subsceneAPI) (1.9.5)`

I can try the new environment even if that's not really convenient.

Does the error means I'm missing a file or something like that ?

**Comment by s-4-m-a-n** [comment]
Why don't you try CLI usage ? If you are still getting error, please send the screenshot.

**Comment by s-4-m-a-n** [comment]
Why don't you try CLI usage ? If you are still getting error, please send the screenshot.

**Comment by hugo-px** [comment]
CLI does work, which is nice ! But i need to integrate your API to a python script that I have, so having it worked on Jupyter would be ideal really.

Here's a screenshot : 
![image](https://user-images.githubusercontent.com/64846704/81085701-da5fd000-8ef7-11ea-9833-508251f73c4e.png)

**Comment by s-4-m-a-n** [comment]
Sometime we get this weird error on file name conflict. Is it is possible
to sent me the screenshot of director folder. Or you can do it by yourself,
just rename the file (.ipynb) and other file of the same folder.

**Comment by hugo-px** [comment]
Just did it, here's a screenshot :
![image](https://user-images.githubusercontent.com/64846704/81087802-6d016e80-8efa-11ea-8d27-64722d6fd9f7.png)

This gets me another error message : 
![image](https://user-images.githubusercontent.com/64846704/81087884-86a2b600-8efa-11ea-91fc-9eb3584a5543.png)

Did i do what you said correctly ?

**Comment by s-4-m-a-n** [comment]
Change the main folder's name bs4 into whatever you want but not bs4.

**Comment by hugo-px** [comment]
Did it, same error :

![image](https://user-images.githubusercontent.com/64846704/81088896-ebaadb80-8efb-11ea-98b0-67fcdbe3eb77.png)

**Comment by s-4-m-a-n** [comment]
resend me a screenshot of the directory. And run the code "from bs4 import
Beautifulsoup" saperately.

**Comment by hugo-px** [comment]
Here's the new directory :
C:\Users\...\anaconda3\Lib\site-packages\bs4_2

![image](https://user-images.githubusercontent.com/64846704/81091069-f87cfe80-8efe-11ea-8a63-af066332e72d.png)

**Comment by hugo-px** [comment]
If I run this : 
from bs4_2 import Beautifulsoup

Still the same error occurs :

![image](https://user-images.githubusercontent.com/64846704/81091347-6295a380-8eff-11ea-9787-d7d913aa0f91.png)



(Thanks for your help btw)

**Comment by s-4-m-a-n** [comment]
No man you cannot import Beautifulsoup from bs4_2 .... you have to import it
from bs4 ..... and why don't you restart anaconda and jupyter notebook.

**Comment by hugo-px** [comment]
Sorry this is a bit confusing :/
I restared everything. The folder is still renamed bs4_2. 
from bs4 import Beautifulsoup still gets me the same error : 
ModuleNotFoundError: No module named 'bs4'

**Comment by s-4-m-a-n** [comment]
Try to reinstall subsceneAPI, may be because of the previous issue bs4 is
not properly installed.

**Comment by hugo-px** [comment]
It worked ! Seems like uninstalling everything, erasing the bs4 file from the site-packages/ folder and then reinstall subsceneAPI did the trick.

Thanks a lot for your help !
